/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamBookingRouteImport } from './routes/exam-booking'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificationsIndexRouteImport } from './routes/certifications.index'
import { Route as CertificationsSlugRouteImport } from './routes/certifications.$slug'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamBookingRoute = ExamBookingRouteImport.update({
  id: '/exam-booking',
  path: '/exam-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsIndexRoute = CertificationsIndexRouteImport.update({
  id: '/certifications/',
  path: '/certifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsSlugRoute = CertificationsSlugRouteImport.update({
  id: '/certifications/$slug',
  path: '/certifications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/exam-booking': typeof ExamBookingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/training': typeof TrainingRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/certifications/': typeof CertificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/exam-booking': typeof ExamBookingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/training': typeof TrainingRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/certifications': typeof CertificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/exam-booking': typeof ExamBookingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/training': typeof TrainingRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/certifications/': typeof CertificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/corporate'
    | '/dashboard'
    | '/exam-booking'
    | '/login'
    | '/signup'
    | '/training'
    | '/certifications/$slug'
    | '/certifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/corporate'
    | '/dashboard'
    | '/exam-booking'
    | '/login'
    | '/signup'
    | '/training'
    | '/certifications/$slug'
    | '/certifications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/corporate'
    | '/dashboard'
    | '/exam-booking'
    | '/login'
    | '/signup'
    | '/training'
    | '/certifications/$slug'
    | '/certifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CorporateRoute: typeof CorporateRoute
  DashboardRoute: typeof DashboardRoute
  ExamBookingRoute: typeof ExamBookingRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TrainingRoute: typeof TrainingRoute
  CertificationsSlugRoute: typeof CertificationsSlugRoute
  CertificationsIndexRoute: typeof CertificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-booking': {
      id: '/exam-booking'
      path: '/exam-booking'
      fullPath: '/exam-booking'
      preLoaderRoute: typeof ExamBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/': {
      id: '/certifications/'
      path: '/certifications'
      fullPath: '/certifications/'
      preLoaderRoute: typeof CertificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/$slug': {
      id: '/certifications/$slug'
      path: '/certifications/$slug'
      fullPath: '/certifications/$slug'
      preLoaderRoute: typeof CertificationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CorporateRoute: CorporateRoute,
  DashboardRoute: DashboardRoute,
  ExamBookingRoute: ExamBookingRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TrainingRoute: TrainingRoute,
  CertificationsSlugRoute: CertificationsSlugRoute,
  CertificationsIndexRoute: CertificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
